name: train-my-model
on: 
  pull_request:
    branches: [ "ml-experiments-develop" ]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd experiments
          pip3 install -r experiment_requirements.txt
          python create_model.py

          # Create CML report
          cat metrics.txt >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}